spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    defer-datasource-initialization: true
openweathermap.key: ${OPENAPI_KEY}
logging.config: classpath:logback-spring.xml
